---

- name: Ensure ~/.ssh directory exists on remote host
  ansible.builtin.file:
    path: "{{ user_home }}/.ssh"
    state: directory
    mode: "0700"
  become: false

- name: Deploy automation SSH key pair
  ansible.builtin.import_tasks: deploy_automation_key.yml

- name: Configure SSH client for github.com
  ansible.builtin.import_tasks: ssh_config.yml

- name: Get real execution user
  ansible.builtin.command: whoami
  register: current_os_user
  changed_when: false
  become: false
  tags: [ssh_authorized]

- name: Inject FIDO2 public keys into authorized_keys
  ansible.posix.authorized_key:
    user: "{{ current_os_user.stdout }}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/dots/ssh_keys/' + item + '.pub') }}"
    comment: "FIDO2 {{ item }}"
  loop: "{{ ssh_key_pairs }}"
  tags: [ssh_authorized]
