[mac]
localhost ansible_connection=local

[linux]
vps ansible_host=69.62.77.27 ansible_user=vps ansible_ssh_user=vps
master-node ansible_host=192.168.29.22 ansible_user=master-node
server-node ansible_host=192.168.29.11 ansible_user=server-node

[linux:vars]
ansible_python_interpreter=/usr/bin/python3
