---


dotfiles_repo_url: git@github.com:TanishBhandari286/ansible-managed-dots.git

dotfiles_dir: "{{ ansible_facts['user']['dir'] | default(ansible_facts['env']['HOME']) }}/dots"


ssh_automation_key: id_ed25519_ansible

ssh_key_pairs:
  - id_ed25519_sk_key1
  - id_ed25519_sk_key2
