---

linux_packages:
  - zsh
  - git
  - curl
  - wget
  - unzip
  - ripgrep
  - fd-find
  - fzf
  - tmux
  - htop
  - bat
  - tree
  - neovim
  - python3
  - python3-pip
  - build-essential
  - zsh-syntax-highlighting
  - zsh-autosuggestions
