return {
  {
    "folke/snacks.nvim",
    opts = {
      scratch = { enabled = true },
      zen = { enabled = true },
    },
    -- Unused shortcuts, unbound so they stop cluttering which-key. Setting the
    -- same lhs/mode with `false` as the rhs tells lazy.nvim's keys handler to
    -- never bind it -- see lazy.core.handler.keys.resolve.
    -- stylua: ignore
    keys = {
      { "<leader>.", false },
      { "<leader>S", false },
      { "<leader>z", false },
      { "<leader>,", false },
      { "<leader>:", false },
      { "<leader>fb", false },
      { "<leader>fB", false },
      { "<leader>fc", false },
      { "<leader>fF", false },
      { "<leader>fg", false },
      { "<leader>fr", false },
      { "<leader>fR", false },
      { "<leader>fp", false },
      { "<leader>gd", false },
      { "<leader>gD", false },
      { "<leader>gs", false },
      { "<leader>gS", false },
      { "<leader>gi", false },
      { "<leader>gI", false },
      { "<leader>gp", false },
      { "<leader>gP", false },
      { "<leader>sb", false },
      { "<leader>sB", false },
      { "<leader>sg", false },
      { "<leader>sG", false },
      { "<leader>sp", false },
      { "<leader>sw", false, mode = { "n", "x" } },
      { "<leader>sW", false, mode = { "n", "x" } },
      { '<leader>s"', false },
      { "<leader>s/", false },
      { "<leader>sa", false },
      { "<leader>sc", false },
      { "<leader>sC", false },
      { "<leader>sd", false },
      { "<leader>sD", false },
      { "<leader>sh", false },
      { "<leader>sH", false },
      { "<leader>si", false },
      { "<leader>sj", false },
      { "<leader>sk", false },
      { "<leader>sl", false },
      { "<leader>sM", false },
      { "<leader>sm", false },
      { "<leader>sR", false },
      { "<leader>sq", false },
      { "<leader>su", false },
      { "<leader>uC", false },
    },
  },
}
